name: Deploy to Neocities

on:
  push:
    branches: [ main ]      # każdy push na main uruchamia deploy
  workflow_dispatch:         # ręczne odpalenie z UI

concurrency:
  group: neocities-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove files that must NOT be uploaded
        run: |
          rm -rf .git .github .gitignore .gitattributes

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: .
          cleanup: false
          protected_files: |
            favicon.svg
            favicon.ico
