name: Deploy to Neocities

on:
  push:
    branches: [ main ]   # jeśli pracujesz na innej gałęzi, zmień tu
  workflow_dispatch:      # ręczne odpalenie z zakładki Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          neocities_site: romionologic      # dokładnie nazwa Twojej strony na Neocities
          dist_dir: .                        # wysyłamy cały katalog repo (root)
          clean: true                        # usuń z serwera pliki, których nie ma w repo (opcjonalnie)
